### ISSUE TITLE
VLAN Changes

### ISSUE THREAD

**Issue by nichswall** [fortinet-ansible-dev/ansible-galaxy-fortiswitch-collection#4]
Hello

We are trying to do a basic change of native_vlans and allowed_vlans; however the job keeps failing. Looking at the fortiswitch dbug logs, it is trying to "rename "port3" to "interface'" and then edit "interface" instead of "port3" Below are the ansible play and the debug log

Ansible Pay:

![image](https://user-images.githubusercontent.com/86736486/169877129-7d8ce4fe-3460-4c06-9c0e-4818391e7253.png)

Fortiswitch log:

![image](https://user-images.githubusercontent.com/86736486/169877959-1ef77024-dcb3-4084-a4bd-deb1c2cb4b25.png)

**Comment by MaxxLiu22** [comment]
Hi @nichswall ,

Thank you for raising this issue and sorry for any inconvenience. I can reproduce this issue on my side and have reported it to the development team. I will let you know if there are any updates

Thanks,
Maxx

**Comment by borgermeister** [comment]
Any progress on this issue?

**Comment by JieX19** [comment]
Hi @borgermeister 

We've fixed the bug and will have a release soon. I will keep you posted once it's released.

Thanks,
Jie

**Comment by JieX19** [comment]
Hi @nichswall @borgermeister,

Could you help confirm if this module works well on your side? I tested it in my lab and it works.

Thanks,
Jie

**Comment by borgermeister** [comment]
Great stuff.
I’m on a short vacation but will try this in my lab when I get back.

**Comment by JieX19** [comment]
Hi @borgermeister 

I will close the issue at this moment, marking it as resolved or completed. If you have any further questions or concerns, please feel free to reopen the ticket or create a new one.
